columnSuffix: null
contentColumnType: string
fieldGroup: 917431a5-6e7c-4bac-82cc-6ed8acdaec51 # Entry Fields
handle: imageData
instructions: ''
name: 'Image Data'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:245afdaf-6be5-47e9-b0f0-00f2e1bfbf64' # Entries
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:245afdaf-6be5-47e9-b0f0-00f2e1bfbf64' # Entries
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
