defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  62b6628f-db05-4628-96ab-4b76671ce74b: # Tech Task
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
